### ISSUE TITLE
Integrate function returns error

### ISSUE THREAD

**Issue by samuelbrown21** [MorrissyLab/mosaicMPI#31]
After generating a .config file using the default command and then running mosaicMPI integrate, I get this error:
![image](https://github.com/user-attachments/assets/dde9d36a-87ad-491d-95a2-163527e1ed13)

I'm not sure if maybe it's because I'd like to integrate the dataset with itself? I'm also not sure exactly what this error is saying. I know there are programs discovered as I've generated the heatmaps. 

Thank you! 

Samuel

**Comment by verheytb** [comment]
Thank you for reporting this issue! It is not related to integrating the programs from a single dataset (this is a supported use of `mosaicmpi integrate`). It was a bug from a recent refactorization. It has been fixed in 2.6.7, so please update to the latest version and rerun `mosaicmpi integrate` as you did before.
